// Autogenerated from Pigeon (v0.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTPlayer;
@class FLTBattingStats;
@class FLTPitchingStats;
@class FLTLikeMessage;

@interface FLTPlayer : NSObject
@property(nonatomic, copy, nullable) NSString * name;
@property(nonatomic, strong, nullable) NSNumber * number;
@property(nonatomic, copy, nullable) NSString * position;
@property(nonatomic, strong, nullable) NSNumber * war;
@property(nonatomic, strong, nullable) FLTBattingStats * battingStats;
@property(nonatomic, strong, nullable) FLTPitchingStats * pitchingStats;
@property(nonatomic, strong, nullable) NSNumber * isLiked;
@end

@interface FLTBattingStats : NSObject
@property(nonatomic, strong, nullable) NSNumber * pa;
@property(nonatomic, strong, nullable) NSNumber * avg;
@property(nonatomic, strong, nullable) NSNumber * obp;
@property(nonatomic, strong, nullable) NSNumber * slg;
@property(nonatomic, strong, nullable) NSNumber * woba;
@property(nonatomic, strong, nullable) NSNumber * fld;
@property(nonatomic, strong, nullable) NSNumber * war;
@end

@interface FLTPitchingStats : NSObject
@property(nonatomic, strong, nullable) NSNumber * ip;
@property(nonatomic, strong, nullable) NSNumber * k9;
@property(nonatomic, strong, nullable) NSNumber * bb9;
@property(nonatomic, strong, nullable) NSNumber * babip;
@property(nonatomic, strong, nullable) NSNumber * era;
@end

@interface FLTLikeMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * number;
@end

@interface FLTApi2Flutter : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)showPlayer:(FLTPlayer*)input completion:(void(^)(NSError*_Nullable))completion;
@end
@protocol FLTApi2Host
-(void)likePlayer:(FLTLikeMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTApi2HostSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTApi2Host> _Nullable api);

NS_ASSUME_NONNULL_END
